version: "3"

services:
  my-service:
    container_name: nginx-modsec
    build: 
      dockerfile: Dockerfile
      context: ./nginx-php-modsec-fluentd/
    restart: always
    ports: 
      - "8899:80"

  my-elastic:
    container_name: my-elastic
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.0"
    hostname: elastic
    restart: always
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment: 
      - discovery.type=single-node

  my-kibana:
    container_name: my-kibana
    image: "docker.elastic.co/kibana/kibana:7.5.0"
    hostname: kibana
    restart: always
    ports: 
      - "5601:5601"
    links:
      - "my-elastic:elasticsearch"
